services:
  - type: web
    name: health-prediction-platform
    env: docker
    plan: free
    dockerFilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DEBUG
        value: 'false'
      - key: ALLOWED_HOSTS
        value: '*'
databases:
  - name: health-db
    plan: free
    databaseName: healthpredict
    user: healthuser
