services:
  - type: web
    name: health-prediction-platform
    env: docker
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DEBUG
        value: 'true'
      - key: ALLOWED_HOSTS
        value: '*'
      - key: DJANGO_SUPERUSER_USERNAME
        value: 'admin'
      - key: DJANGO_SUPERUSER_PASSWORD
        value: 'admin123'
      - key: DJANGO_SUPERUSER_EMAIL
        value: 'admin@healthpredict.com'

databases:
  - name: health-db
    region: oregon
    plan: free
    databaseName: healthpredict
    user: healthuser
