services:
  - type: web
    name: health-prediction-platform
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfile: ./Dockerfile
    dockerContext: .
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DEBUG
        value: 'false'
      - key: ALLOWED_HOSTS
        value: '*'

databases:
  - name: health-db
    region: oregon
    plan: free
    databaseName: healthpredict
    user: healthuser
