services:
  - type: web
    name: health-prediction-platform
    env: docker
    plan: free
    dockerFilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DEBUG
        value: 'false'
      - key: ALLOWED_HOSTS
        value: '*'
    buildCommand: ""
    startCommand: "gunicorn --chdir healthpredict healthpredict.wsgi:application --bind 0.0.0.0:10000"
databases:
  - name: health-db
    plan: free
    databaseName: healthpredict
    user: healthuser
